### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by whadar** [Peer5/peer5-docs#26] opened 2016-06-07 18:55 UTC
Docs should run on https

![image](https://cloud.githubusercontent.com/assets/922633/15870856/7a6da090-2cfa-11e6-82d1-d39d7b843276.png)

**Comment by mrbar42** [comment] 2016-06-07 20:14
Duplicate of #22

**Comment by whadar** [comment] 2016-06-19 12:36
Let's get this done before the rest of the related issues, since it's quick and important

**Comment by shaharmor** [comment] 2016-06-19 12:50
Done.
@whadar should this be https only?

**Comment by shaharmor** [comment] 2016-06-19 13:47
Made https-only

**Closed by shaharmor** 2016-06-19 13:47 UTC
Labels: priority:normal, status:in-progress, type:improvement
